[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino

; ===== OTA 無線燒入設定 =====
; 首次需透過 USB 燒入，之後可用 WiFi 燒入
; upload_protocol = espota
; upload_port = 192.168.50.158  ; ESP32 的 IP 位址

lib_deps =
  madhephaestus/ESP32Encoder@^0.11.7
  Dlloydev/QuickPID@^3.1.9
  madhephaestus/ESP32Servo@^3.0.6
  https://github.com/HuskyLens/HUSKYLENSArduino/archive/refs/heads/master.zip
  https://github.com/adafruit/Adafruit_SSD1306.git
  https://github.com/adafruit/Adafruit-GFX-Library.git
  https://github.com/adafruit/Adafruit_BusIO.git
